### ISSUE TITLE
RGB Whitespace Syntax not recognized

### ISSUE THREAD

**Issue by hennessyevan** [KamiKillertO/vscode-colorize#389]
Whitespace syntax is a valid CSS RGB syntax but is not supported by this extension.
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#RGB_syntax_variations

<img width="227" alt="image" src="https://user-images.githubusercontent.com/16711653/81103155-a4622200-8ede-11ea-96be-21799ded1c06.png">

**Comment by firefoxic** [comment]
It is important not to forget about supporting the same syntax for `hsl()`:
```css
.class {
  --a: hsl(12 34% 56%);
  --a: hsl(12deg 34% 56%);
  --a: hsl(12 34% 56% / 0.78);
  --a: hsl(12deg 34% 56% / 0.78);
}
  ```
  Each of the options is valid syntax.
